### ISSUE TITLE
将拉勾中爬下来的所有数据都存入数据库。

### ISSUE THREAD

**Issue by raychou1203** [GuozhuHe/webspider#14]
想要将拉勾中爬下来的所有数据都存入数据库应该使用哪条命令？
```
# 启动定时任务分发器
env/bin/celery_beat
```
是定期启动所有爬虫吗？

**Comment by fishkao** [comment]
提个新需求：提取某一种职业要求

对某一个行业职位要求的标签提取，能计算出每年对某一种职位的的标签的变迁
1. 长期霸版的为基础技能标签
2. 近2年新增的标签

Title的类型的分布，比如同样的产品经理，又分了前端、后端、B端、C端、商业、增长等，输出一个title的分布

1.  分析出产品经理的通用职能需求
2.  每一种产品经理的偏向性技术要求标签

**Comment by GuozhuHe** [comment]
现在没有时间~~~

yilan <notifications@github.com> 于2019年3月4日周一 下午9:22写道：

**Comment by GuozhuHe** [comment]
是的 这个是celery的定时任务 还需要开worker配合


Yang Zhou <notifications@github.com> 于2019年1月26日周六 下午2:58写道：
