### ISSUE TITLE
# 您好，请问下这些常量的配置是什么？

### ISSUE THREAD

**Issue by dx524404832** [GuozhuHe/webspider#15]
# 您好，请问下这些常量的配置是什么？
JOB_JSON_URL = “”
JOB_DETAIL_URL = “”
COMPANY_DETAIL_URL = “”
ALL_CITY_URL = “”
COMPANIES_URL = “”
COMPANY_JOBS_URL = “”

**Comment by GuozhuHe** [comment]
可以翻一翻历史版本的代码，里面有的

**Comment by dx524404832** [comment]
您好  打扰了 我想问下 我在你的提交记录里面找到的配置，我用了下，请求的Json文件报：操作太平凡，清稍后再试

想问下：你请求的内容都是直接请求的json文件吗？如果请求的页面的内容会报json解析错误

发送自 Windows 10 版邮件应用

发件人: GuozhuHe
发送时间: 2019年5月27日 10:30
收件人: GuozhuHe/webspider
抄送: dx524404832; Author
主题: Re: [GuozhuHe/webspider] # 您好，请问下这些常量的配置是什么？ (#15)

可以翻一翻历史版本的代码，里面有的
